name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          # Chỉ điểm cho GitHub biết file lock nằm ở 2 thư mục con
          cache-dependency-path: |
            1_nest_backend/package-lock.json
            2_Remotion_Video/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./1_nest_backend
        run: npm ci

      - name: Generate Prisma Client
        working-directory: ./1_nest_backend
        run: npx prisma generate

      - name: Build Backend
        working-directory: ./1_nest_backend
        run: npm run build

      - name: Run Backend Tests
        working-directory: ./1_nest_backend
        run: npm run test

      - name: Install Remotion Dependencies
        working-directory: ./2_Remotion_Video
        run: npm ci

      - name: Build Remotion Project
        working-directory: ./2_Remotion_Video
        run: npm run build